# build.yaml — ZMK firmware build matrix
# ─────────────────────────────────────────────────────────
# Used by GitHub Actions to build firmware for each half.
# Add additional boards here as you expand your collection.
#
# Board definitions live in: boards/arm/tornblue/
# Keymap and config live in: config/
---
include:
  - board: tornblue_left
  - board: tornblue_right
